import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./style.css";
import "./custom.css";
import Sidebar from './common/sidebar';
import Topbar from './common/topbar';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vatsalya",
  description: "Generated by Uma Jadhav",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <div className="ves_main">
          <Sidebar />

          <Topbar />



          {children}

        </div>


      </body>
    </html>
  );
}
